version: "3"

volumes:
  mongodata:
  
services:
      
  mongo:
    container_name: Mongo
    image: mongo:4.4
    restart: always
    environment:
      TZ: "America/Guayaquil"
      MONGO_INITDB_ROOT_USERNAME: "CRobalino"
      MONGO_INITDB_ROOT_PASSWORD: "O6i5a2o7"
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27017:27017
    networks:
      - arobalink

networks:
  arobalink:
    driver: bridge
    name: arobalink